# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 700)
        MainWindow.setStyleSheet("background-color: rgb(120, 145, 226)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, 0, 1391, 70))
        self.label.setStyleSheet("font: 20pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);\n"
"  width: 100px;\n"
"  margin: 0 auto;\n"
"  background-color: rgb(76, 1, 101);\n"
"  height: 300px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1170, 10, 161, 51))
        self.label_2.setStyleSheet("font: 17pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 90, 311, 30))
        self.label_3.setStyleSheet("font: 20pt \"Open Sans\";\n"
"color:rgb(90, 8, 80);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 120, 1000, 20))
        self.label_4.setStyleSheet("color:rgb(255, 169, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 150, 850, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 200, 551, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 250, 531, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 310, 541, 20))
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 200, 80, 26))
        self.pushButton.setStyleSheet(" background-color: rgb(57, 255, 0);\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 250, 80, 26))
        self.pushButton_2.setStyleSheet(" background-color: rgb(57, 255, 0);\n"
"border-radius: 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(950, 200, 80, 26))
        self.pushButton_3.setStyleSheet(" background-color: rgb(255, 97, 0);\n"
"border-radius: 10px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(950, 250, 80, 26))
        self.pushButton_4.setStyleSheet(" background-color: rgb(255, 97, 0);\n"
"border-radius: 10px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 360, 26, 26))
        self.pushButton_5.setStyleSheet("font: 16pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(76, 1, 101);\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(770, 360, 26, 26))
        self.pushButton_6.setStyleSheet("font: 16pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(76, 1, 101);\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(620, 360, 26, 26))
        self.pushButton_7.setStyleSheet("font: 16pt \"Open Sans\";\n"
"border-radius:10px;\n"
"\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(76, 1, 101);\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(650, 360, 26, 26))
        self.pushButton_8.setStyleSheet("font: 16pt \"Open Sans\";\n"
"color:rgb(76, 1, 101);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(680, 360, 26, 26))
        self.pushButton_9.setStyleSheet("font: 16pt \"Open Sans\";\n"
"color:rgb(76, 1, 101);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(880, 520, 150, 35))
        self.pushButton_10.setStyleSheet(" background-color: rgb(64, 64, 64);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(210, 440, 500, 35))
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border-radius: 4px;\n"
" border: 1px solid black;\n"
"  padding: 5px;\n"
"")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 520, 350, 35))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border-radius: 4px;\n"
" border: 1px solid black;\n"
"  padding: 5px;\n"
"")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(590, 520, 250, 35))
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border-radius: 4px;\n"
" border: 1px solid black;\n"
"  padding: 5px;\n"
"")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(720, 440, 300, 35))
        self.pushButton_14.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border-radius: 4px;\n"
" border: 1px solid black;\n"
"  padding: 5px;\n"
"")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 410, 181, 18))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 490, 181, 18))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(590, 490, 181, 18))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(720, 420, 181, 18))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Панель Администратора"))
        self.label_2.setText(_translate("MainWindow", "Выход"))
        self.label_3.setText(_translate("MainWindow", "Список пользователей"))
        self.label_4.setText(_translate("MainWindow", "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.label_5.setText(_translate("MainWindow", "№                              Имя                           Логин                    Пароль                Роль в системе                Изменить                 Удалить"))
        self.label_6.setText(_translate("MainWindow", "1                               Иван                           12313                        123                   Администратор               "))
        self.label_7.setText(_translate("MainWindow", "2                               Петько                        2131231                    123                       Менеджер              "))
        self.label_8.setText(_translate("MainWindow", "3                              Сидор                          опла213                   123                          Аналитик             "))
        self.pushButton.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_2.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_4.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_5.setText(_translate("MainWindow", "<"))
        self.pushButton_6.setText(_translate("MainWindow", ">"))
        self.pushButton_7.setText(_translate("MainWindow", "1"))
        self.pushButton_8.setText(_translate("MainWindow", "2"))
        self.pushButton_9.setText(_translate("MainWindow", "3"))
        self.pushButton_10.setText(_translate("MainWindow", "Создать"))
        self.label_9.setText(_translate("MainWindow", "Введите имя фамилию"))
        self.label_10.setText(_translate("MainWindow", "Введите логин"))
        self.label_11.setText(_translate("MainWindow", "Введите пароль"))
        self.label_12.setText(_translate("MainWindow", "Введите роль"))
